# Generated by Django 4.2.16 on 2024-09-18 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lists",
            fields=[
                ("list_id", models.AutoField(primary_key=True, serialize=False)),
                ("listname", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lists",
            },
        ),
        migrations.CreateModel(
            name="Sentences",
            fields=[
                ("sentences_id", models.AutoField(primary_key=True, serialize=False)),
                ("sentences", models.CharField(max_length=200)),
                ("meaning", models.CharField(blank=True, max_length=50, null=True)),
                ("lemma", models.CharField(blank=True, max_length=50, null=True)),
                ("note", models.CharField(blank=True, max_length=200, null=True)),
                ("word_start_pos", models.IntegerField()),
                ("word_end_pos", models.IntegerField()),
                (
                    "list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="word_lists.lists",
                    ),
                ),
            ],
            options={
                "db_table": "sentences",
            },
        ),
    ]
