# Generated by Django 5.1.4 on 2025-01-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_lists', '0002_sentences_appear_times_sentences_fail_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentences',
            name='appear_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sentences',
            name='fail_times',
            field=models.IntegerField(default=0),
        ),
    ]
