# Generated by Django 5.1.4 on 2025-01-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_lists', '0004_settings'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='settings',
            table='settings',
        ),
    ]
